#ifndef DOOMBSP_H
#define DOOMBSP_H

#include "common.h"
#include "m_line.h"
#include "doomdata.h"
#include "array.h"
#include "next.h"

#include <math.h>
#include <stdbool.h>

#define PI	3.141592657


// -----------------------------------------------------------------------------
// doombsp Types

typedef	struct
{
	NXPoint	pt;
    float	dx;
    float   dy;
} divline_t;

typedef struct bspstruct_s
{
	Array *				    lines_i;		// if non NULL, the node is
	divline_t				divline;		// terminal and has no children
	float					bbox[4];
	struct bspstruct_s		*side[2];
} bspnode_t;

typedef struct
{
	NXPoint		p1, p2;
    int			linedef; // index into linestore_i
    int         side; // 0 = front, 1 = back
    int         offset; // End of the segment.
	bool		grouped; // internal error check
} line_t; // This is really a segment!


// -----------------------------------------------------------------------------
// doombsp

extern bool draw;


// -----------------------------------------------------------------------------
// doomload
// TODO: remove doomload.c
extern	Array	*linestore_i, *thingstore_i;

/// Populate node builder arrays `linestore_i` and `thingstore_i`, skipping
/// any invalid data. Coordinates are translated from SDL back to NeXT.
/// - Author: Thomas Foster
void NB_LoadMap(void);


// -----------------------------------------------------------------------------
// drawing

extern SDL_Window * nbWindow;
extern SDL_Renderer * nbRenderer;
extern SDL_Texture * nbTexture;

extern	NXRect		worldbounds;

void NB_DrawLine(float x1, float y1, float x2, float y2);
void NB_Refresh(int delayMS);
void EraseWindow (void);
void NB_DrawMap (void);

/// Draws all of the lines in the given storage object.
/// - note: This handles arrays of both `line_t` and `Line`!
void DrawLineStore (Array * lines_i);
void DrawDivLine (divline_t *div);
void DrawLineDef (maplinedef_t *ld);


// -----------------------------------------------------------------------------
// buildbsp

extern int cuts; // number of new lines generated by BSP process
extern bspnode_t * startnode;

void BuildBSP (void);
void DivlineFromWorldline (divline_t *d, line_t *w);
int	PointOnSide (NXPoint *p, divline_t *l);


// -----------------------------------------------------------------------------
// savebsp

extern	Array * secstore_i;
extern	Array * mapvertexstore_i;
extern	Array * subsecstore_i;
extern	Array * maplinestore_i;
extern	Array * nodestore_i;
extern	Array * mapthingstore_i;
extern	Array * ldefstore_i;
extern	Array * sdefstore_i;

void SaveDoomMap (void);


// -----------------------------------------------------------------------------
// saveblocks

void SaveBlocks (void);


// -----------------------------------------------------------------------------
// savesectors

void ProcessSectors (void);
void BuildSectordefs (void);

// -----------------------------------------------------------------------------
// saveconnect

void ProcessConnections (void);
void OutputConnections (void);

// -----------------------------------------------------------------------------
// doombsp

void DoomBSP(void);

#endif /* DOOMBSP_H */
